# Dockerfile (dev environment)
FROM maven:3.9.8-eclipse-temurin-17

WORKDIR /app

# Cài đặt make utility
RUN apt-get update \
    && apt-get install -y \
        make \
        lsof \
        net-tools \
        iproute2 \
        psmisc \
        procps \
    && rm -rf /var/lib/apt/lists/*

# Không build source, chỉ giữ container chạy để có thể exec vào
CMD ["tail", "-f", "/dev/null"]
